version: '3'
services:
  proxy:
    image: traefik
    container_name: traefik
    restart: always
    command: --web --docker --docker.domain=domain.local --logLevel=DEBUG
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - dmz
      - frontoffice
    labels:
      - "traefik.frontend.rule=Host:traefik.domain.local"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=infra_dmz"

  mysql-db:
    image: percona/percona-server
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=mattermost
    volumes:
      - mysql-db:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - backoffice
    labels:
      - "traefik.enable=false"

  mattermost:
    image: pixhub/mattermost
    container_name: mattermost
    depends_on: 
      - mysql-db
    restart: always
    environment:
      - DB_USER=root
      - DB_HOST=mysql-db
      - DB_NAME=mattermost
    volumes:
      - mattermost-data:/opt/mattermost/data
      - mattermost-cfg:/opt/mattermost/config
    networks:
      - frontoffice
      - backoffice
    labels:
      - "traefik.frontend.rule=Host:mattermost.domain.local"
      - "traefik.backend=mattermost"
      - "traefik.port=8065"
      - "traefik.docker.network=infra_frontoffice"

networks:
  dmz:
    driver: bridge
  frontoffice:
    driver: bridge
  backoffice:
    driver: bridge

volumes:
  mattermost-data:
  mattermost-cfg:
  mysql-db:
